# Generated by Django 5.0.6 on 2025-09-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("database", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(
                blank=True,
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Usuario",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="documento_numero",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Número de documento"
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="documento_tipo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DNI", "DNI"),
                    ("CE", "Carnet de Extranjería"),
                    ("PASSPORT", "Pasaporte"),
                ],
                max_length=10,
                null=True,
                verbose_name="Tipo de documento",
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["username"], name="users_usernam_baeb4b_idx"),
        ),
    ]
