# Generated by Django 5.0.6 on 2025-09-16 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0002_user_username_alter_student_documento_numero_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/photos/%Y/%m/",
                verbose_name="Foto de perfil",
            ),
        ),
    ]
