# Generated by Django 5.0.6 on 2025-10-07 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0003_user_photo"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpaqueSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_token",
                    models.CharField(
                        db_index=True,
                        help_text="Token opaco generado aleatoriamente",
                        max_length=64,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "expires_at",
                    models.DateTimeField(help_text="Fecha de expiración de la sesión"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="IP desde donde se creó la sesión",
                        null=True,
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(blank=True, help_text="User-Agent del cliente"),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Si la sesión está activa"
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("web", "Web Browser"),
                            ("mobile", "Mobile App"),
                            ("api", "API Client"),
                            ("admin", "Admin Panel"),
                        ],
                        default="web",
                        help_text="Tipo de cliente que creó la sesión",
                        max_length=20,
                    ),
                ),
                (
                    "session_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Datos adicionales de la sesión",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Usuario propietario de la sesión",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opaque_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesión Opaca",
                "verbose_name_plural": "Sesiones Opacas",
                "db_table": "opaque_sessions",
            },
        ),
        migrations.CreateModel(
            name="SessionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("access", "Page Access"),
                            ("api_call", "API Call"),
                            ("extend", "Session Extended"),
                            ("invalidate", "Session Invalidated"),
                        ],
                        max_length=20,
                    ),
                ),
                ("endpoint", models.CharField(blank=True, max_length=200)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="database.opaquesession",
                    ),
                ),
            ],
            options={
                "verbose_name": "Actividad de Sesión",
                "verbose_name_plural": "Actividades de Sesión",
                "db_table": "session_activities",
            },
        ),
        migrations.AddIndex(
            model_name="opaquesession",
            index=models.Index(
                fields=["session_token"], name="opaque_sess_session_b86dbc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opaquesession",
            index=models.Index(
                fields=["user", "is_active"], name="opaque_sess_user_id_8f4ad8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opaquesession",
            index=models.Index(
                fields=["expires_at"], name="opaque_sess_expires_5c07d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="opaquesession",
            index=models.Index(
                fields=["last_activity"], name="opaque_sess_last_ac_999fc6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionactivity",
            index=models.Index(
                fields=["session", "timestamp"], name="session_act_session_5187f0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionactivity",
            index=models.Index(
                fields=["activity_type", "timestamp"],
                name="session_act_activit_bf9033_idx",
            ),
        ),
    ]
