# Generated by Django 5.0.6 on 2025-10-07 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0004_opaquesession_sessionactivity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="opaquesession",
            name="jwt_token_hash",
            field=models.CharField(
                blank=True,
                help_text="Hash HMAC-SHA256 del JWT token",
                max_length=64,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="opaquesession",
            name="jwt_token_id",
            field=models.CharField(
                blank=True,
                help_text="ID del JWT token interno (OutstandingToken)",
                max_length=255,
                null=True,
            ),
        ),
    ]
