# Generated by Django 5.0.6 on 2025-10-07 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0005_opaquesession_jwt_token_hash_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="opaquesession",
            name="session_token",
            field=models.CharField(
                db_index=True,
                help_text="HASH HMAC-SHA256 del token opaco (nunca el token original)",
                max_length=64,
                unique=True,
            ),
        ),
    ]
