# Generated by Django 5.0.6 on 2025-10-08 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0006_convert_session_tokens_to_hash"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.URLField(
                blank=True,
                max_length=500,
                null=True,
                verbose_name="Foto de perfil (URL)",
            ),
        ),
    ]
