# Generated by Django 5.0.6 on 2025-10-09 22:40
# JWT PURO - Modelos opaque eliminados del código

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0009_cleanup_jwt_puro'),
    ]

    operations = [
        # Los modelos OpaqueSession y SessionActivity han sido eliminados del código
        # Las tablas ya fueron eliminadas en la migración 0009_cleanup_jwt_puro
        # Esta migración marca que el estado del modelo está sincronizado
    ]
