# Generated by Django 5.0.6 on 2025-10-10 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0010_auto_20251009_2240'),
    ]

    operations = [
        # Esta migración elimina los modelos OpaqueSession que ya no se usan
        # en el sistema JWT puro. Los modelos fueron eliminados del models.py
        # por lo que esta migración está vacía pero es necesaria para mantener
        # la consistencia del historial de migraciones.
    ]