# Generated by Django 5.0.6 on 2025-10-10 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0011_remove_opaque_models"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sessionactivity",
            name="session",
        ),
        migrations.DeleteModel(
            name="OpaqueSession",
        ),
        migrations.DeleteModel(
            name="SessionActivity",
        ),
    ]
