# Generated by Django 5.0.6 on 2025-10-12 11:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "database",
            "0012_remove_sessionactivity_session_delete_opaquesession_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Avatar",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("url", models.URLField(max_length=500, verbose_name="URL del Avatar")),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("PRACTICANTE", "Practicante"),
                            ("SUPERVISOR", "Supervisor"),
                            ("COORDINADOR", "Coordinador"),
                            ("SECRETARIA", "Secretaria"),
                            ("ADMINISTRADOR", "Administrador"),
                        ],
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Nombre descriptivo",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
            ],
            options={
                "verbose_name": "Avatar",
                "verbose_name_plural": "Avatares",
                "db_table": "avatars",
                "indexes": [
                    models.Index(fields=["role"], name="avatars_role_674bf6_idx"),
                    models.Index(
                        fields=["is_active"], name="avatars_is_acti_e2c174_idx"
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="database.avatar",
                verbose_name="Avatar",
            ),
        ),
    ]
