# Generated by Django 5.0.6 on 2025-10-12 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0013_avatar_user_avatar"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
    ]
