# Generated by Django 5.0.6 on 2025-10-12 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("database", "0014_remove_photo_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="avatar",
            name="name",
        ),
    ]
