# Generated by Django 5.0.6 on 2025-11-02 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0017_add_relations_to_presentation_letter'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='presentationletterrequest',
            name='pres_lett_escuela_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='presentationletterrequest',
            name='pres_lett_empresa_status_idx',
        ),
        migrations.AlterModelTable(
            name='company',
            table='upeu_empresa',
        ),
        migrations.AlterModelTable(
            name='practice',
            table='upeu_practica',
        ),
        migrations.AlterModelTable(
            name='role',
            table='upeu_rol',
        ),
        migrations.AlterModelTable(
            name='user',
            table='upeu_usuario',
        ),
    ]
